### ISSUE TITLE
Feature Request: an in-browser export tool for saving results as Excel/CSV/etc

### ISSUE THREAD

**Issue by VIDGuide** [kviklet/kviklet#108]
Something like https://github.com/DataTables/DataTablesSrc but this is quite old, I'm sure there are probably much nicer react components that can do the same thing. Be nice to be able to just click a button and export the results that came back as a CSV file.

**Comment by Askir** [comment]
Good one, noted. Will take this up soon.

One thing on my mind is that currently any select loads the full response into memory and then pushes it to the frontend. If people do sensible selects with where clauses this is not a big issue but if you do `select *` on a huge table, you're bound to run into memory problems eventually.

A "download as CSV" button ideally streams the result directly from the DB, avoiding the memory issues. And the normal select can then be limited to a few hundred/thousand rows.
Just need to figure out a way to only enable this for select statements to avoid duplicate execution of deletes, updates and DDL requests as these wont be idempotent.

**Comment by VIDGuide** [comment]
CSV is perfectly sufficient! I'll update ECS soon and give it a shot, thanks!
