### ISSUE TITLE
Add notification and alert for Kviklet

### ISSUE THREAD

**Issue by nh4ttruong** [kviklet/kviklet#110]
Notification feature is necessary for _"approval"_ application like Kviklet. And I think that it will be greater if Kviklet has notification/alert like **Webhook** or **SMTP** for `approver` and `requester`, i.e:
- Requester raise a request -> Alert to Approver
- Approver approved that request -> Alert to Requester
- TemporarySession timeout -> Alert

Content in notification also needs to have some fields like "**approver**", "**requester**", "**message**", "**request_url**", "**approve_url**",...

Hope that it will be appear in next release, thank team!

**Comment by Askir** [comment]
Slack/teams and email notifications are definitely coming. But I don't think already in the next release sorry :( I think there is still some more pressing things to fix and do.

Would you mind sharing what notification integration you would need though? So I can at least prioritize the tooling you are personally using?

**Comment by nh4ttruong** [comment]
Thank for your update, I also think Slack/Teams is popular tool for notification integration and I'm using them ^^. Could I know which version the release air is?

**Comment by VIDGuide** [comment]
I'd vote for Teams, if you're looking for popularity :)

**Comment by Askir** [comment]
I'll actually do this next week, I think it fits the theme of "support teams of 10+ people" that I am going for with v0.4 😁 
It'll probably be basic and I don't want to link accounts yet but then you can at least have a teams channel linked where new requests and reviews are posted or something like that.

**Comment by Askir** [comment]
@VIDGuide @nh4ttruong I have merged #128 which allows you to configure a webhook URL.
New Requests that require review as well as new Reviews will then be alerted about in your configured channel.

I did not implement any kviklet-account to chat-app-user synchronization yet which would allow for more personalized notifications but I think this is a decent start.

If you have more specific wishes/requirements for your workflows, feel free to create a follow up ticket though! 😄

**Comment by Askir** [comment]
Btw it's kinda bullshit that Microsoft doesn't offer any sort of free tier for teams anymore. I had to sign up for a 30 day trial of Microsoft 365 but once that runs out I don't really have a way to test the integration anymore.

If anyone has worked with the teams webhooks before and has a good way of testing things, would be very happy about any tips.

If I don't touch it I'll assume it continues working, but especially to see how the message formatting actually  looks it would be good to have a way to actually try it out 😅
