### ISSUE TITLE
Add LDAP support

### ISSUE THREAD

**Issue by DerkSchooltink** [kviklet/kviklet#122]
Adding LDAP support for providing authentication (and potentially also authorization via LDAP groups) would be beneficial for organisations that use this instead of some SAML implementation as identity provider.

Spring seems to [support it out of the box](https://spring.io/guides/gs/authenticating-ldap), although I'm unsure how well it fits within the existing code base. I'm willing to contribute potentially. Just wanted to drop this issue here now as placeholder and see if other people are interested too.

**Comment by Askir** [comment]
I've never implemented an LDAP login yet, but will gladly have a look. Usually Spring is okay with existing standards, but it sometimes a hassle to enable it for multiple at once.
Regarding authorization, I see the need and I also have SAML group sync on my todo list but it's a bit more complicated and quite the enterprise feature I think, so I'll probably delay it a bit longer.

**Comment by Askir** [comment]
Alright, it was a bit of a pain to even setup a local LDAP server without ever having worked with it but I think I got it working in: #155 . The standard really feels quite dated to me and a bit over-engineered, but I suppose it's also flexible enough to support most orgs setups.
I have tried to make all relevant fields configurable, I would be very happy if you could try it out with your setup @DerkSchooltink and let me know if it works or if something is missing!

**Comment by DerkSchooltink** [comment]
It all works perfectly fine! Thanks a lot for your contributions! @Askir
