### ISSUE TITLE
Add option to explicitly deny a request for access

### ISSUE THREAD

**Issue by DerkSchooltink** [kviklet/kviklet#123]
In order to avoid having stale requests never being cleaned up, I think it makes sense to be able to explicitly deny a request. This will then move it to a separate view where all explicitly denied requests are shown.

**Comment by Askir** [comment]
If I keep close to the Github Pull Request analogy, the reviewer can Request changes but anyone can also close the PR. I'll think a bit about what version makes most sense for Kviklet, you're definitely right that there should be a way to deny a request permanently.

**Comment by Askir** [comment]
Finally got to do this in #152 .
You can now chose to Request Changes on a request which blocks it from being executed until the intial change requester has approved (similar to how github change request works).
And you can also choose to flat out reject a request which prevents it from ever being executed.
