### ISSUE TITLE
Database selection on query request submission

### ISSUE THREAD

**Issue by DerkSchooltink** [kviklet/kviklet#124]
Kviklet allows you to create connections to a specific database on a specific Postgres/MySQL instance. This becomes cumbersome when a single instance contains multiple databases:

![image](https://github.com/kviklet/kviklet/assets/22047701/3c70bec9-4648-44eb-8ded-58b219e8619a)

Creating a separate connection for each one of the databases is required in order to make this work. This is a lot of work. 

My suggestion would be to allow for a selection of database during the submission of the query/access request. A simple dropdown with the available databases to pick from would greatly reduce setup required for a connection.

**Comment by Askir** [comment]
This is a good idea but actually a bit confusing to implement, because I think schemas in mysql are actually called databases, while postgres has the separation as your graphic shows. Then how JDBC calls it... I'm not even sure. Definitely something that could be more intuitive and easier though.

**Comment by Askir** [comment]
I just merge #158, and went with attacking this complaint directly:
> Creating a separate connection for each one of the databases is required in order to make this work

You can now test your connection in the create connection screen, this step then also checks if the user has access to multiple databases and if yes allows you to create a connection for each one, with the click of a button.

Looks like this:
<img width="400" alt="Screenshot 2024-07-10 at 15 40 35" src="https://github.com/kviklet/kviklet/assets/10251955/35d4d05f-3100-4caa-abac-89150b063fab">

Hope this helps!

**Comment by DerkSchooltink** [comment]
Awesome, thanks a lot for the effort! I will test this as soon as I see the Docker image appearing. :)
