### ISSUE TITLE
Only Admin Can Approve?

### ISSUE THREAD

**Issue by tarunmittal24** [kviklet/kviklet#156]
Is there any way by which we can create the role in such a way that only guys having this role, can approved it and then the developer will access the db, otherwise one dev can create the request and other can approve and get the db access.

By the way perfect tool which i am looking for.

**Comment by Askir** [comment]
That'll come in one way or another in v0.5.
Currently creating requests and reviewing is the same permission sadly so I cant even tell you to edit the permissions manually, sorry.
> one dev can create the request and other can approve and get the db access.

This is how I originally intended the tool, but I get that different organizations have different requirements around this especially depending on the data and organizational setup in which you're operating.

I've been struggling a bit with mapping the use cases around required reviews and permissions into a clean UX where there is only one way to achieve something.
I aim to build required reviews in a way that it is configurable to require reviews from specific roles. E.g. require a dev and an ops person to approve or similar. But if I don't restrict the review logic accordingly you'll be able to review even if your role effectively doesn't count towards the requirements.

But I think I just have to live with some extra checks that notify the user accordingly. So yes coming in a few weeks, I'll let you know here when it's done so you can try it out on the `:main` image.

Glad you like it so far though!

**Comment by Askir** [comment]
Okay I went with the minimal solution for now in #160 
You can now give roles individual permission to review. So you can remove this permission for you default roles and then only admins can approve.

Hope this fits your use case.
You'll need to use the most recent `:main` image as 0.5 still will take a few weeks before being released.
