### ISSUE TITLE
Search function in connection overview

### ISSUE THREAD

**Issue by DerkSchooltink** [kviklet/kviklet#165]
In this overview, the connections quickly add up:
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/b0d2f0f7-1c38-4f5f-b6e8-9e36c6d01a7f">

In order to make it easier to find your database, add a search bar that searches on connection name.

Also, the styling could be a little bit better here (overflowing database name in the panel) :P

**Comment by Askir** [comment]
Yeh me and frontend (especially CSS) are still not great friends sometimes. I will try fix this.
Took the search bar into the feature list for 0.5 although by now it's unlikely that every feature makes it.
I think this one should not be so difficult.

**Comment by Askir** [comment]
I fixed the styling in #168 at least. Search probably next week.

**Comment by Askir** [comment]
Also merged the search bar now in #175 :D
