### ISSUE TITLE
Bug in creating multiple connections for each database found during connection creation

### ISSUE THREAD

**Issue by DerkSchooltink** [kviklet/kviklet#166]
The ID that is used for each connection appends the ID of the previous connection. This causes multiple issues:
1. It is just plain ugly, not representable for the actual database used in the connection
2. The maximum length is exceeded for creating a lot of connections (or databases with long names)

I will submit a PR with an attempt to fix this.

**Comment by Askir** [comment]
Thank you so much for providing a fix PR, merged it!

Bit of an embarrassing bug tbh, I didn't really realize this while testing it somehow.
