### ISSUE TITLE
MariaDB connection type

### ISSUE THREAD

**Issue by ameliagaskin** [kviklet/kviklet#196]
Hello, 

Would it be possible to add MariaDB to the list of connection types? I can connect with MYSQL database to my local MariaDB but it would be clearer that the database I am connecting to is the same as the connection type. 

Thank you, 
Amelia

**Comment by landbaychrisburrell** [comment]
Hi Askir

They try their best to keep the connection protocol the same, so should be the same however, there are a few differences for example in the configuration of TLS as well as several optimizations around batch queries or returns of larger tables I believe, etc.

**Comment by Askir** [comment]
Alright, good to know.
I merged #203 now. So you are able to select MariaDB as a separate connection type and it will use the mariadb jdbc connector instead of the mysql one.

Hope this helps!
