### ISSUE TITLE
Remove database connections

### ISSUE THREAD

**Issue by ameliagaskin** [kviklet/kviklet#201]
Hello, 

Just a small thing, is there a way to remove database connections through the interface? 

Thank you, 
Amelia

**Comment by Askir** [comment]
There is in fact not anymore. I redesigned this a while ago, and removed that button. Forgot to add it back 😅 
Will look into adding it again tomorrow.

You can however edit a connection almost completely freely (except for the id). So maybe you can repurpose it in the meantime 😇

**Comment by Askir** [comment]
Fixed in #206 :)
