### ISSUE TITLE
Save button in General Setting doesn't send any request

### ISSUE THREAD

**Issue by sapisuper** [kviklet/kviklet#224]
Hi found issue when update slack webhook url in General Setting. When I click Save button there is not sending any request.
![image](https://github.com/user-attachments/assets/6a9b5aea-6f9a-4059-9aa8-a35d8c4cb7db)

Workaround I do manual update the value slack Url in source database kviklet.

Please check. thank you

**Comment by Askir** [comment]
Thanks for raising that, fixed it in #225 and will make a 0.5.1 release for it as well

**Comment by sapisuper** [comment]
@Askir I will check later for the update. thank you 👍
