### ISSUE TITLE
Database Protocol MongoDB automatic change to MONGODB

### ISSUE THREAD

**Issue by sapisuper** [kviklet/kviklet#227]
Hi I just try to add new connection MongoDB with database protocol MONGODB_SRV. but after successful add connection the database protocol automatic change to MONGODB. 

![image](https://github.com/user-attachments/assets/921d50dd-a0a6-4ce6-8865-8df4b0a47ea9)

workaround to solve this issue is modify connection database protocol to MONGODB_SRV again.

thank you

**Comment by Askir** [comment]
Thank you for finding that one, fixed in #229 !
You're truly the best QA haha 😅 sorry for bringing such buggy things into releases sometimes. I already added more e2e tests, but the smaller stuff is a bit harder to catch.

**Comment by sapisuper** [comment]
@Askir hahaha no prob. thanks btw for fix that
