### ISSUE TITLE
Access release time

### ISSUE THREAD

**Issue by eduardo-mbochip** [kviklet/kviklet#234]
Hello! I would like to leave a tip that would be to be able to define the time that the user will have access, since the time currently is 1 hour.

Is there any way to increase this time by editing a configuration file?

Thank you and keep up the good work on the project! :)

**Comment by Askir** [comment]
That's right access requests currently time out 1 hour after starting the session.
There is currently no way to configure this. But I considered making it selectable in request creation (with a default configurable per connection).

Do you think this would help?
Just out of curiosity do you want to make it longer or shorter?

**Comment by eduardo-mbochip** [comment]
I would like to leave the time longer.

Thanks for your feedback!

**Comment by Askir** [comment]
@eduardo-mbochip Hi, I've just merged #242 which allows you to configure a custom access duration for requests. You can also set the time to zero which would allow the request to be active indefinitely. Hope this helps! Don't hesitate to reach out if there are any problems.
