### ISSUE TITLE
Request Expiry Time Customization & Full-time DB Access for Users

### ISSUE THREAD

**Issue by vjmax** [kviklet/kviklet#237]
I have a couple of questions regarding access requests in KvikeT:

**Request Expiration after 60 minutes**: When I approve a request, it seems to expire after 60 minutes by default. Is there a way to change this expiration limit? If possible, I’d like to adjust it based on different use cases.

**Full-time DB Access for Specific Users:** Is it possible to grant full-time access to a specific user for a particular database? Instead of temporary access, we would like to give continuous access to certain trusted users for some of our databases.

**Comment by Askir** [comment]
Hi, you're the second person requesting customization of the temporary access time in the last week haha.
I'm on it probably will be merged by end of week!

Regarding permanent access. You can create specific connections that require no approvals and give only your trusted users access to these connections. They would still have to create requests but then do not need any approvals for those. And with the temporary access duration change I will also add an infinite option, which you could then use for "permanent" sessions.

Hope this helps.

**Comment by Askir** [comment]
Hey @vjmax I just merged #242 which allows you to configure a custom access time when creating a request. If you set this time to zero the session will be active indefinitely.

Hope this helps! Let me know if you run into any issues.
