### ISSUE TITLE
Error pull new image 

### ISSUE THREAD

**Issue by eduardo-mbochip** [kviklet/kviklet#243]
Hello,

I'm trying to pull the latest image of the application, but it's not working. Below is the image with the Time Out error.

![Screenshot from 2024-09-24 11-15-01](https://github.com/user-attachments/assets/805ae580-95ee-4aa5-8965-6dca7c2900a4)

Could you check if everything is ok with the image?

Thank you

**Comment by Askir** [comment]
Hmm, that's odd.
I noticed some flakyness in github actions earlier as well. Maybe Github had some issues? It works for me right now. Could you try again some time?

**Comment by eduardo-mbochip** [comment]
Hello!

Now I got it! Thank you very much for your feedback.

**Comment by Askir** [comment]
Great that it works again 👍 If this is a common occurence I am up to find an alternative image registry. But so far its the first time this has happened.
