### ISSUE TITLE
Compatibility with Prisma?

### ISSUE THREAD

**Issue by hongkongkiwi** [kviklet/kviklet#252]
Very cool!

I'm interested to use this with Prisma migrations and seeding. Prisma has a lot of built in SQL generation.

From my understanding I would have to use the proxy, but then how does it work with approval of the SQL changes?

I'm wondering if it would break prisma because prisma expects to apply the changes itself.

**Comment by Askir** [comment]
I wouldn't use Kviklet for migrations. It's not really designed for that. Usually your migrations would be stored in version control and then you can enforce review policies on changes to that so you won't need a separate approval tool for this.

The proxy is also only temporary e.g. when you run it is bound to a particular user who is allowed access for some time.
