### ISSUE TITLE
MSSQL Support

### ISSUE THREAD

**Issue by VIDGuide** [kviklet/kviklet#85]
Just wondering how much work do you think would be involved in adding MSSQL support, given there are JDBC drivers for it?

**Comment by Askir** [comment]
Probably not very difficult. JDBC is the reason we went with the jvm ecosystem in the first place 😄

I'll look into it next week.

**Comment by Askir** [comment]
Just merged #87. I had to set `encrypt=true; trustServerCertificate=true;` to make it work with the official MS SQL server 2022 docker image, but depending on your setup it might also work with the normal certificate chain.

I will release a new version some time early in may. But the container published from main already contains the change so feel free to use that. Let me know if you run into any issues!

**Comment by VIDGuide** [comment]
Amazing, thanks so much. I'll give this a whirl very soon!

**Comment by VIDGuide** [comment]
In my case, I needed
`;encrypt=false;trustServerCertificate=true;`
the leading semi-colon seemed to be the tricky bit. the UI prompts an example with a question mark, but the semi-colon made it work.

**Comment by VIDGuide** [comment]
![image](https://github.com/kviklet/kviklet/assets/3220618/739a12bd-90d5-4174-930a-b328b78e99e4)

Just wanted to let you know the team I work with is already very appreciative for this tool; we're still just on read only so far, but it's really helping bridge the gap of letting our operations team leads fetch and verify data they need for further operations! 

So just some positive feedback for you :)

**Comment by Askir** [comment]
Thank you so much! 

There is still a long list of features ahead that I want to build, but it's very motivating to see that it's already improving workflows in the current state!
